### ISSUE TITLE
Replacing pip freeze.

### ISSUE THREAD

**Issue by katsika** [naiquevin/pipdeptree#104]
Hey, great tool! Thanks!

Wanted to replace pip freeze and only save top level packages with pipdeptree. Tried to run `pipdeptree -f` and got a nice output after grepping it accordingly. Problem is, that one of the packages I want to control version of is not a top level package, well, it is (it's Django), I installed it separately, but because it has dependant packages it does not show as top level package for freezing purposes.

This is not a bug or a problem with pipdeptree itself, I just need to figure out how to avoid manually adding frozen version of django package to requirements file after each pipdeptree invocation. Tried to use `-a` but it would add many packages alongside django, which I am not interested in tracking.

Any ideas?

Thanks.

**Comment by naiquevin** [comment]
Hi, I missed this issue somehow, sorry about it. You might be able to achieve the above with following command,

```
pipdeptree --freeze | grep -Pi '^\w+|django' | sed 's/ //g'
```
