### ISSUE TITLE
Incompatible with pip 18.1

### ISSUE THREAD

**Issue by Midnighter** [naiquevin/pipdeptree#105]
The newest pip release 18.1 finally moved their API around and pipdeptree no longer works.

```
Traceback (most recent call last):
  File "/home/moritz/.virtualenvs/test-cobra/lib/python3.6/site-packages/pipdeptree.py", line 17, in <module>
    from pip._internal import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions'
```

Somehow I was under the impression that pipdeptree was not using the internal pip API but that's obviously wrong. Importing from a module marked as `_internal` seems... less than ideal :grimacing:

**Comment by zachliu** [comment]
I hereby confirm this incompatibility :joy:
