### ISSUE TITLE
Shouldn't `local_only` be `True` by default?

### ISSUE THREAD

**Issue by devxpy** [naiquevin/pipdeptree#111]
I was writing a plugin system for pip that works across virtualenvs. (Install plugin once on global python, and then it works on all virtualenvs)

Naturally, I tried writing a plugin for pipdeptree.

The only problem is that pipdeptree puts `local_only` as `False` by default, which means invoking it from a virtualenv causes it to show all global packages. 

---

- This can be fixed by vendoring pipdeptree in the plugin itself, and running with `python -I ...` (isolated mode) but that looks too fragile.

- It can also be fixed by the plugin, by just translating and hacking on the command line arguments.

But `local_only=True` feels like a sensible default, especially when `get_installed_distributions()` has this signature -

```
Signature: get_installed_distributions(local_only=True, skip={'python', 'argparse', 'wsgiref'}, include_editables=True, editables_only=False, user_only=False)
```

I am happy to author a pull request if that's okay :)

**Comment by naiquevin** [comment]
The `--local-only` flag is exactly the same as `--local` flag of `pip freeze` which also has false as the default. 

Does your plugin system require the virtualenvs to have access to global site-packages? Because the `--local`/`--local-only` flag is only applicable in that case.

**Comment by devxpy** [comment]
>The --local-only flag is exactly the same as --local flag of pip freeze

Right, makes sense!

>Does your plugin system require the virtualenvs to have access to global site-packages? 

Not necessarily.
But it currently does that, so the plugin doesn't have to vendor pipdeptree. 

Either that or we must integrate plugin with pipdeptree itself. But I guess that's too much to ask when it's not even merged into master yet!?

(FWIW, it's takes like a [single line](https://github.com/pycampers/pip-plugin-collection/blob/9eb47c15ed344623c9f5227c427a00813e011013/pip_plugin_collection.py#L8)  and import for making the plugin).

We're currently having a discussion over at https://github.com/pypa/pip/issues/3999.

**Comment by devxpy** [comment]
I just noticed https://github.com/naiquevin/pipdeptree/issues/2. Hopefully, this plugin system will solve user confusions like these...

**Comment by naiquevin** [comment]
Hi, 

First of all, sorry for the late response. 

> Either that or we must integrate plugin with pipdeptree itself. But I guess that's too much to ask when it's not even merged into master yet!?

I didn't get this. What is not merged in master yet? 

I briefly glanced through `pip-plugin-collection` and I guess there's some overlap  of functionality with `pipenv` (Although this could be incorrect as I don't use `pipenv` myself).

**Comment by devxpy** [comment]
Sorry, never mind. 

This issue was created in a hope that pip-master accepts my request for a plugin system. But I don't think they are very keen on the idea.

`pip-plugin-collection` was a simple demonstration of what _can_ be done if there was some functionality in `pip` itself, for a plugin system.
