### ISSUE TITLE
Tests out of sync with test-data

### ISSUE THREAD

**Issue by jayvdb** [naiquevin/pipdeptree#116]
I created new test data today, and I assume that my tests are failing because new versions have been released since the tests were written, and were included in my venvs.

```console
[   15s] =================================== FAILURES ===================================
[   15s] ___________________________ test_render_tree_exclude ___________________________
[   15s] tests/test_pipdeptree.py:148: in test_render_tree_exclude
[   15s]     assert expected == tree_str
[   15s] E   AssertionError: assert 'alembic==0.9...kzeug==0.14.1' == 'alembic==0.9....kzeug==0.14.1'
[   15s] E       alembic==0.9.10
[   15s] E         - Mako [required: Any, installed: 1.0.7]
[   15s] E     -   - python-dateutil [required: Any, installed: 2.7.3]
[   15s] E     ?                                                  ^ ^
[   15s] E     +   - python-dateutil [required: Any, installed: 2.8.0]
[   15s] E     ?                                                  ^ ^
[   15s] E     -     - six [required: >=1.5, installed: 1.11.0]
[   15s] E     ?                                           ^
[   15s] E     +     - six [required: >=1.5, installed: 1.12.0]
[   15s] E     ?                                           ^
[   15s] E     -   - python-editor [required: >=0.3, installed: 1.0.3]
[   15s] E     ?                                                    ^
[   15s] E     +   - python-editor [required: >=0.3, installed: 1.0.4]
[   15s] E     ?                                                    ^
[   15s] E     - click==6.7
[   15s] E     + Click==7.0
[   15s] E       Flask-Script==2.0.6
[   15s] E       gnureadline==6.3.8
[   15s] E       Jinja2==2.10
[   15s] E       Lookupy==0.1
[   15s] E       Mako==1.0.7
[   15s] E       psycopg2==2.7.5
[   15s] E     - python-dateutil==2.7.3
[   15s] E     ?                    ^ ^
[   15s] E     + python-dateutil==2.8.0
[   15s] E     ?                    ^ ^
[   15s] E     -   - six [required: >=1.5, installed: 1.11.0]
[   15s] E     ?                                         ^
[   15s] E     +   - six [required: >=1.5, installed: 1.12.0]
[   15s] E     ?                                         ^
[   15s] E     - python-editor==1.0.3
[   15s] E     ?                    ^
[   15s] E     + python-editor==1.0.4
[   15s] E     ?                    ^
[   15s] E       redis==2.10.6
[   15s] E     - six==1.11.0
[   15s] E     ?         ^
[   15s] E     + six==1.12.0
[   15s] E     ?         ^
[   15s] E       slugify==0.0.1
[   15s] E       Werkzeug==0.14.1
[   15s] _______________________ test_render_tree_exclude_reverse _______________________
[   15s] tests/test_pipdeptree.py:173: in test_render_tree_exclude_reverse
[   15s]     assert expected == tree_str
[   15s] E   AssertionError: assert 'alembic==0.9...kzeug==0.14.1' == 'alembic==0.9....kzeug==0.14.1'
[   15s] E       alembic==0.9.10
[   15s] E     - click==6.7
[   15s] E     ?        ^ ^
[   15s] E     + click==7.0
[   15s] E     ?        ^ ^
[   15s] E       Flask-Script==2.0.6
[   15s] E       gnureadline==6.3.8
[   15s] E       Jinja2==2.10
[   15s] E       Lookupy==0.1
[   15s] E       Mako==1.0.7
[   15s] E         - alembic==0.9.10 [requires: Mako]
[   15s] E       psycopg2==2.7.5
[   15s] E     - python-dateutil==2.7.3
[   15s] E     ?                    ^ ^
[   15s] E     + python-dateutil==2.8.0
[   15s] E     ?                    ^ ^
[   15s] E         - alembic==0.9.10 [requires: python-dateutil]
[   15s] E     - python-editor==1.0.3
[   15s] E     ?                    ^
[   15s] E     + python-editor==1.0.4
[   15s] E     ?                    ^
[   15s] E         - alembic==0.9.10 [requires: python-editor>=0.3]
[   15s] E       redis==2.10.6
[   15s] E     - six==1.11.0
[   15s] E     ?         ^
[   15s] E     + six==1.12.0
[   15s] E     ?         ^
[   15s] E     -   - python-dateutil==2.7.3 [requires: six>=1.5]
[   15s] E     ?                        ^ ^
[   15s] E     +   - python-dateutil==2.8.0 [requires: six>=1.5]
[   15s] E     ?                        ^ ^
[   15s] E           - alembic==0.9.10 [requires: python-dateutil]
[   15s] E       slugify==0.0.1
[   15s] E       Werkzeug==0.14.1
[   15s] =========================== short test summary info ============================
[   15s] FAIL tests/test_pipdeptree.py::test_render_tree_exclude
[   15s] FAIL tests/test_pipdeptree.py::test_render_tree_exclude_reverse
[   15s] ===================== 2 failed, 27 passed in 2.56 seconds ======================
```

Ideally the pickle files, and virtualenv's site-packages, could be provided as a static tgz with each release, so that the release can be re-tested continually using that data.

**Comment by naiquevin** [comment]
Hi, 

Yeah, I am aware of this. The tests have been in a bad state for some time now. I am planning to completely rewrite them in bash (or python) where pipdeptree is installed in a virtualenv, dependencies installed, pipdeptree run all in a subprocess. Assertions will be made based on stdout/stderr. 

I did consider the approach that you've suggested - providing archived virtualenv but I have observed that tests with fresh setup have been able to catch compatibility (with pip mostly) related bugs on a number of occasions. 

Hopefully I'll get time to pick it up soon! 

Regards, 
Vineet

**Comment by jayvdb** [comment]
You, and the end user, should still be able to do fresh data and tests.

I am only asking that a snapshot of the data is made with each release, so that sdist testers can verify the tests run as expected at the time of the release.  It could be stored in a different repo, or added as a GitHub release artifact, or stored in the sdist, or could be added to PyPI as a release artifact by uploading it using a distinctive fake 'platform' identifier so it isnt downloaded accidentally by real users.

e.g. see the openSUSE package I created at
https://build.opensuse.org/package/show/devel:languages:python/python-pipdeptree

In the .spec file I needed to omit two tests because my data is different from the venvs at release date.

Also it would be nice to reduce the size of the test data.  18.6 MB isnt unacceptably large, but I am sure we can trim out a lot of stuff from the venv to make the tgz smaller.

**Comment by naiquevin** [comment]
Hi, 

I don't have an understanding of how OpenSUSe packaging works. Why do you need the a frozen test setup at the time of release to be included in the package? Or rather at what all points in the entire package management workflow are the tests (defined in the `.spec` file) run?

**Comment by jayvdb** [comment]
The test suite that is included in each release is constantly re-run whenever there is any change in any dependency.
It could be a patch applied to Python itself, a new version of setuptools, etc.
The tests are also run on various platforms, which vary by architecture, Python version, and some are quite old under long term release support (e.g. SLE_12_SP4 at https://build.opensuse.org/package/show/devel:languages:python/python-pipdeptree), while Tumbleweed is a rolling release.

The tests must pass before the .spec is accepted, so in this case I have disabled the two tests which rely on historical data I havent re-created.  After that point, if the tests start failing, it indicates some other part of the system either regressed or intentionally broke, and packagers need to find the source of the problems, and were it seems unintentionally the packagers then raise bugs upstream to highlight that they have broken other packages.  e.g. if a release of pip breaks pipdeptree, they may be unaware.  If it seems unintentional, we might decide to not release the new version of pip and wait for the fix to arrive.

**Comment by naiquevin** [comment]
Hi, 

Sorry for a late reply. You mention that once the .spec is accepted the tests are run again (I am assuming periodically?) and may fail. In case of pipdeptree, tests may fail even if a python dependency is installed differently because of newer version of pip. In other words if snapshot of the test setup created at the time of pipdeptree's release is used for running tests at a later time, it might not catch compatibility issues due to newer version of pip installing the dependencies differently. 

Firstly, this is has been observed in past but is very rare, and secondly these doesn't result in failure but just unexpected output/behaviour. Nevertheless it would be good to catch such cases, IMO. I've already started fixing the tests in another branch by completely getting rid of the pickle files and doing a fresh install every time.

However, I'm busy with other priorities at the moment, so can't promise a date for this.

**Comment by naiquevin** [comment]
The older test suite has been replaced with a new one which is purely unit tests against mocked objects. Hence the complicated test setup is no longer required. This change is in master and a beta release `2.0.0b1` but hasn't be released as a stable version yet (Planning to do it in a couple of weeks time). 

Closing this issue.
