### ISSUE TITLE
When using --graph-output and -p, the output file contains all installed packages deps.

### ISSUE THREAD

**Issue by jd-naranjo** [naiquevin/pipdeptree#117]
When using --graph-output and -p, the output file's graph contains all installed packages deps.
I would expect the graph contains only the selected packages and dependencies. 
When I use the -p option alone I do see the expected selected content. When additionally use the --graph-output flag, the option -p is simply ignored, but I would like to see the graph of the selected packages only.

**Comment by naiquevin** [comment]
Hi, this has been a known issue and there was an attempt to fix it earlier but had to be reverted as it broke other things (See #87). 

This tool was originally written with just printing the output to stdout/stderr in mind and graph support was added later. So the fix will require fair amount of refactoring. I am planning to pick it up after the current task that I am working on, which is sorting out the tests which have become messy and flaky over time.

**Comment by naiquevin** [comment]
A pre-release version 2.0.0b1 has been pushed to pypi that fixes this. A stable 2.0.0 version will be released soon. Closing the issue.
