### ISSUE TITLE
Requirements with square brakects

### ISSUE THREAD

**Issue by KristofHorvath** [naiquevin/pipdeptree#136]
Dependency tree is incorrect if any of the package names contains square brackets. For example requirements.txt of firebase-admin lists google-api-core[grpc]; however, the relevant row of the output of `pipdeptree -p firebase-admin` is `- google-api-core [required: >=1.14.0,<2.0.0dev, installed: 1.22.4]`, so [grpc] is missing.

**Comment by naiquevin** [comment]
I think by square brackets you mean extra requirements. There's an open PR #132 for this.

**Comment by KristofHorvath** [comment]
Thank you.
