### ISSUE TITLE
pip-licenses lists pkg-resources==0.0.0

### ISSUE THREAD

**Issue by g3n35i5** [naiquevin/pipdeptree#143]
pipdeptree seems to list `pkg-resources==0.0.0` as dependency but this is a known bug in pip freeze & ubuntu, see https://github.com/pypa/pip/issues/4022 for more information.
Some packages may list this requirement, but I think it should be filtered out.

**Comment by naiquevin** [comment]
If it's a bug in pip, I'd prefer to not do any special handling for it and wait for it to be fixed in pip itself. 

That said, it should be easy to exclude it from pipdeptree's output as follows, 

```
    pipdeptree -e pkg-resources
```

Please do let me know if it works?

**Comment by g3n35i5** [comment]
You are right, probably a separate treatment of this error is not useful. Excluding the package works, I think I will be fine with it. 
Thanks for the quick reply, I'll close the issue :)
