### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frenzymadness** [naiquevin/pipdeptree#159]
Hello.

Is there any plan for a new release soon? I'm currently facing the problem with the latest graphviz problem which seems to be fixed in the latest commits in the master branch.

Have a nice day.

**Comment by naiquevin** [comment]
@frenzymadness I'll release it by this weekend.

**Comment by naiquevin** [comment]
Published version 2.2.1 to pypi - https://pypi.org/project/pipdeptree/
