### ISSUE TITLE
Confusing Dependencies section should not display non-conflicting dependencies

### ISSUE THREAD

**Issue by thedrow** [naiquevin/pipdeptree#20]
For example:

```
* django-guardian==1.2.2 -> Django [installed: 1.6.5]
  djrill==1.0.0 -> Django [required: >=1.3, installed: 1.6.5]
  django-mptt==0.6.1 -> Django [required: >=1.4.2, installed: 1.6.5]
  django-cors-headers==0.12 -> Django [required: >=1.4, installed: 1.6.5]
```

All of them require Django above a certain version. Since none of those packages limit the Django version in use there is no conflict (Django 1.4.2 and above is required).

**Comment by naiquevin** [comment]
This has been fixed in the newer version. Closing the issue. Thanks.
