### ISSUE TITLE
Option for reverse mode

### ISSUE THREAD

**Issue by merwok** [naiquevin/pipdeptree#25]
pipdeptree displays all packages with their dependencies.  I would like to see all packages with their dependents, to answer the question “why is X installed”.  What do you think?

**Comment by tommilligan** [comment]
Like the idead - I'm working on a PR for this at the moment.

Possibly related/useful - [pip-autoremove](https://github.com/invl/pip-autoremove) has a ```--leaves``` option which lists all unused modules in an environment.

**Comment by naiquevin** [comment]
Awesome :-)

**Comment by naiquevin** [comment]
Support for reverse mode has been added in the latest release 0.5.0

**Comment by merwok** [comment]
Thanks!
