### ISSUE TITLE
Minor improvements to output readability

### ISSUE THREAD

**Issue by anntzer** [naiquevin/pipdeptree#44]
A few suggestions:
- (recursively) sort the output, instead of having the packages in a semi-random order
- provide a switch that allows limiting the depth of dependencies (possibly using `[...]` as a marker for "deeper dependencies not shown here) or hiding the installed version.
- provide a switch for listing packages that are not dependencies of other packages.

Nice work!

**Comment by naiquevin** [comment]
Thanks. (1) and (2) are good suggestions. (3) can be easily achieved using `grep` on the output of `pipdeptree`.

**Comment by anntzer** [comment]
Actually (3) is not completely trivial via grep either, because you need to check whether the *next* line starts with `  - `.

**Comment by naiquevin** [comment]
It's actually quite simple if you grep for lines not starting with empty space (thanks to the indentation) eg.

```
$ pipdeptree --warn silence | grep -E '^\w+'
```

**Comment by anntzer** [comment]
Good catch.

**Comment by naiquevin** [comment]
Included in the 0.7.0 release on PyPI.
