### ISSUE TITLE
`--freeze` command skips important packages

### ISSUE THREAD

**Issue by jimbocoder** [naiquevin/pipdeptree#51]
This is intentional, but I'm not sure why: https://github.com/naiquevin/pipdeptree/blob/master/pipdeptree.py#L418

This makes `pipdeptree --freeze` insufficient as a replacement for `pip freeze` despite how much nicer it is.

I'm happy to do the PR if there's agreement that all packages should be listed. Just found this project today and got a few other PR ideas - pipdeptree is really helpful!

**Comment by naiquevin** [comment]
The list of skipped packages in the above line of code is passed to the underlying `pip.get_installed_distributions` function from where we get all information about installed packages. When this tool was originally written, IIRC, the default argument value for `skip` was `['setuptools', 'pip', 'python', 'distribute']` and I wanted to add `pipdeptree` to it. That is why it was hardcoded. 

It looks like the default `skip` value is changed now - https://github.com/pypa/pip/blob/master/pip/utils/__init__.py#L327. So it makes sense to update this code as well. PR is always welcome!

**Comment by jimbocoder** [comment]
#52
