### ISSUE TITLE
Removing a package + its dependencies

### ISSUE THREAD

**Issue by szepeviktor** [naiquevin/pipdeptree#53]
Good afternoon!
Is there a strategy to find unused decencies of a package and remove the package and all those dependencies?

**Comment by szepeviktor** [comment]
I was trying with

1. Find all dependencies `pipdeptree -p PKG`
1. Loop through dependencies: Is it install just because PKG? `pipdeptree -r -p DEP` YES if all last leafs in the dependency tree equal PKG
1. Remove DEP
1. `GOTO 10`

**Comment by naiquevin** [comment]
This sounds like a good addition. Unfortunately, I don't have time for it at present. Feel free to implement it and send a pull request :-)

**Comment by naiquevin** [comment]
Not in favour of implementing uninstallation of packages for various reasons. For one, it's a destructive operation which should be left entirely to be run by the user after careful consideration. Another thing is that if `pipdeptree` is run in the global context, then it will have to be run as `root` to be able to uninstall packages.

**Comment by ustcfdm** [comment]
> Not in favour of implementing uninstallation of packages for various reasons. For one, it's a destructive operation which should be left entirely to be run by the user after careful consideration. Another thing is that if `pipdeptree` is run in the global context, then it will have to be run as `root` to be able to uninstall packages.

What about just outputing the packages name that would be uninstalled? As long as a name list is outputted, users can do whatever they want after careful consideration. And 'root' is not required either, because it does not actually execute the uninstall command.
