### ISSUE TITLE
False "Possibly conflicting dependencies found" warning

### ISSUE THREAD

**Issue by szepeviktor** [naiquevin/pipdeptree#55]
```
Warning!!! Possibly conflicting dependencies found:
* cryptography==1.5
 - setuptools [required: >=11.3, installed: 27.1.2]
```

I have pipdeptree 0.7.0 and of course setuptools 27.1.2 is installed.

**Comment by szepeviktor** [comment]
setuptools has
```python
{'key': 'setuptools', '_obj': Requirement.parse('setuptools>=11.3'), 'project_name': 'setuptools', 'dist': None}
```
in https://github.com/naiquevin/pipdeptree/blob/master/pipdeptree.py#L346

**Comment by szepeviktor** [comment]
Thank you very much.

**Comment by szepeviktor** [comment]
AFAIK I can get these modifications by
`pip3 install https://github.com/naiquevin/pipdeptree/archive/master.zip`

**Comment by naiquevin** [comment]
Yes, that should work. I am also planning to release a new version to PyPI today in a while. So you may wait for that if possible.
