### ISSUE TITLE
Listing packages by dependency?

### ISSUE THREAD

**Issue by chrisspen** [naiquevin/pipdeptree#56]
Is there any built-in option to only list packages that have a specific dependency?

I want to upgrade my version of Django, so I'm trying to find which packages I have installed depend on Django so I can check them.

I see there's a `--packages` option, but this only filters by the top-level package, not dependency.

**Comment by naiquevin** [comment]
Yes, you can use `--reverse` with `--packages` (version > 0.5.0). It should show which pkgs depend on a particular pkg.

**Comment by naiquevin** [comment]
This would have worked I guess. Closing the issue. Please reopen if it didn't.
