### ISSUE TITLE
Support user dir

### ISSUE THREAD

**Issue by szepeviktor** [naiquevin/pipdeptree#58]
It would be nice to support user directories as in `pip install --user`

\* Edited

**Comment by naiquevin** [comment]
I can't find the `--user` option in pip ver `9.0.1`? Can you please give more context?

**Comment by szepeviktor** [comment]
Here you are

> all Python distributions support an alternative install location that is specific to a user

https://pip.pypa.io/en/stable/user_guide/#user-installs

**Comment by szepeviktor** [comment]
Thank you for your work.
