### ISSUE TITLE
--json produces flattened output (which looses dependency data)

### ISSUE THREAD

**Issue by pbirnie** [naiquevin/pipdeptree#92]
fantastic tool  - bu I noticed that json produces flattened output

a normal output may include: 
   - artifactory [required: Any, installed: 0.1.17]
    - pathlib [required: Any, installed: 1.0.1]
    - python-dateutil [required: Any, installed: 2.6.1]
      - six [required: >=1.5, installed: 1.10.0]
    - requests [required: Any, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2018.1.18]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.7, installed: 2.6]
      - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
but json format urllib3 appears as  a first level node
[
...
  {
    "dependencies": [],
    "package": {
      "installed_version": "1.22",
      "package_name": "urllib3",
      "key": "urllib3"
    }
  },
...]

but I wanted to prune the dependency tree based on "provided by container" dependencies 
assuming, in this simplified example that 'requests' is 'provided' at runtime on the path

I wanted to prune the json tree  so that urllib3 is not included

Not a big deal -  I will use the text tree output for my pruning

**Comment by pbirnie** [comment]
working on a pull request fix.

**Comment by pbirnie** [comment]
I see there is already a PR with a fix - https://github.com/naiquevin/pipdeptree/pull/91/files

**Comment by naiquevin** [comment]
Hi, I'll look at all the open issues and PRs soon (Really busy at work at present)

**Comment by naiquevin** [comment]
Fixed in latest version `0.11.0` available on pypi.
