### ISSUE TITLE
Changes in pip-10.0.0b2 break pipdeptree

### ISSUE THREAD

**Issue by emddudley** [naiquevin/pipdeptree#95]
`pipdeptree` is broken with `pip-10.0.0b2`.

```
$ pipdeptree -j
Traceback (most recent call last):
  File "/home/someone/venv/bin/pipdeptree", line 11, in <module>
    sys.exit(main())
  File "/home/someone/venv/lib/python2.7/site-packages/pipdeptree.py", line 550, in main
    pkgs = pip.get_installed_distributions(local_only=args.local_only,
AttributeError: 'module' object has no attribute 'get_installed_distributions'
```

I believe this is due to the following item in the [change notes](https://github.com/pypa/pip/blob/release/10.0.0/NEWS.rst) for `pip`:
> Move all of pip's APIs into the pip._internal package, properly reflecting the fact that pip does not currently have any public APIs. ([#4696](https://github.com/pypa/pip/issues/4696), [#4700](https://github.com/pypa/pip/pull/4700))

**Comment by naiquevin** [comment]
Yes, I am aware of the refactoring change (See #83). Will push a fix in a day or two. PR is also welcome. Thanks 👍
