### ISSUE TITLE
pipdeptree cannot run with pip 10 as get_installed_distributions is gone

### ISSUE THREAD

**Issue by cdown** [naiquevin/pipdeptree#98]
Running pipdeptree with no arguments with the recently released pip 10 results in this:

```
Traceback (most recent call last):
  File "/home/cdown/.pyenv/versions/3.6.3/bin/pipdeptree", line 11, in <module>
    sys.exit(main())
  File "/home/cdown/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipdeptree.py", line 550, in main
    pkgs = pip.get_installed_distributions(local_only=args.local_only,
AttributeError: module 'pip' has no attribute 'get_installed_distributions'
```

This seems an intentional API restructuring, see https://github.com/pypa/pip/issues/5154.

**Comment by cdown** [comment]
Ah, I see https://github.com/naiquevin/pipdeptree/issues/95 now.

Either way, pip 10 is now public so this seems more pressing :-)

**Comment by naiquevin** [comment]
I've just pushed version `0.12.0` to pypi for this. Thanks
